on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
permissions:
  contents: read

jobs:
  build-docker-images:
    name: Build Docker images
    # NOTE: The Docker loging command apparently stopped working at some point
    #       probably due to some security changes in either/both GitHub and
    #       Dependabot. To solve this, we do not build docker images here.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker
          # TODO: for a separate issue, try pushing it
          push: false
          load: true
          tags: autosubmit/autosubmit:latest
      
      - name: Test the image
        run: |
          docker run --rm autosubmit/autosubmit:latest autosubmit --version
          # https://github.com/BSC-ES/autosubmit/issues/2359
          docker run --rm autosubmit/autosubmit:latest /bin/bash -c '[ -n $USER ] || exit 1'
